#!/usr/bin/env bash
# setup-copilot.sh — Configure Copilot CLI after authentication.
#
# Handles:
#   - Base plugin installation
#   - BYOK (Bring Your Own Key) model configuration
#   - COPILOT_OFFLINE mode for network isolation
#
# Prerequisites:
#   1. Container created and setup.sh has run
#   2. Copilot CLI authenticated: copilot → /login
#
# Usage (inside container):
#   bash .devcontainer/scripts/setup-copilot.sh
set -euo pipefail

echo "━━━ Copilot CLI Setup ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── 0. Verify Copilot CLI is available ───────────────────────────────────────
if ! command -v copilot &>/dev/null; then
  echo "❌ copilot not found. Run setup.sh first, then authenticate."
  exit 1
fi

# ── 1. Install base plugins ───────────────────────────────────────────────────
# Plugins require authentication. If not logged in, this step will fail with
# a clear error from the CLI — run 'copilot → /login' first.
echo ""
echo "  › Installing base Copilot CLI plugins..."
echo "    (requires authentication — run 'copilot → /login' if this fails)"
echo ""

install_plugin() {
  local plugin="$1"
  if copilot plugin marketplace add "$plugin" 2>&1; then
    echo "    ✓ $plugin"
  else
    echo "    ⚠ $plugin — skipped (check authentication or network)"
  fi
}

install_plugin "microsoft/azure-skills"
install_plugin "github/awesome-copilot"
install_plugin "microsoft/work-iq"

echo ""
echo "    Installed marketplaces:"
copilot plugin marketplace list 2>/dev/null || true

# ── 2. BYOK — Bring Your Own Key ─────────────────────────────────────────────
# Set COPILOT_BYOK_API_KEY and (optionally) COPILOT_BYOK_ENDPOINT in your
# host environment or in .env.local (gitignored) before starting the container.
#
# These env vars are injected into the container via containerEnv in devcontainer.json.
#
# Supported backends (set COPILOT_BYOK_ENDPOINT to the appropriate URL):
#   Azure OpenAI:         https://<resource>.openai.azure.com/
#   OpenAI-compatible:    https://api.openai.com/v1
#   Local (e.g. Ollama):  http://localhost:11434/v1
echo ""
if [[ -n "${COPILOT_BYOK_API_KEY:-}" ]]; then
  echo "  › BYOK: custom model key detected."

  # Write BYOK config to the Copilot config directory.
  # The config file is stored in the persistent auth volume if mounted.
  COPILOT_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/copilot"
  mkdir -p "$COPILOT_CONFIG_DIR"
  BYOK_CONFIG="$COPILOT_CONFIG_DIR/byok.env"

  cat > "$BYOK_CONFIG" <<EOF
# BYOK configuration — generated by setup-copilot.sh
# This file is stored in the persistent auth volume (not tracked by git).
export COPILOT_BYOK_API_KEY="${COPILOT_BYOK_API_KEY}"
EOF

  if [[ -n "${COPILOT_BYOK_ENDPOINT:-}" ]]; then
    echo "export COPILOT_BYOK_ENDPOINT=\"${COPILOT_BYOK_ENDPOINT}\"" >> "$BYOK_CONFIG"
    echo "    Endpoint : $COPILOT_BYOK_ENDPOINT"
  fi

  chmod 600 "$BYOK_CONFIG"
  echo "    Config   : $BYOK_CONFIG (mode 600)"
  echo "    Key      : ${COPILOT_BYOK_API_KEY:0:6}… (truncated for security)"
  echo "  ✓ BYOK configured"
else
  echo "  ℹ BYOK: not configured (COPILOT_BYOK_API_KEY not set)"
  echo "    To enable: set COPILOT_BYOK_API_KEY (and optionally COPILOT_BYOK_ENDPOINT)"
  echo "    in your host environment or in .devcontainer/.env.local, then rebuild."
fi

# ── 3. Offline mode ───────────────────────────────────────────────────────────
echo ""
if [[ "${COPILOT_OFFLINE:-}" == "true" ]]; then
  echo "  ✓ Offline mode  : COPILOT_OFFLINE=true — network requests disabled."
  echo "    Copilot will only use locally available models."
else
  echo "  ℹ Offline mode  : disabled (COPILOT_OFFLINE not set or not 'true')"
  echo "    To enable: set COPILOT_OFFLINE=true in your host env or .env.local."
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Copilot CLI setup complete."
echo ""
echo "  Verify plugins : copilot  →  /plugins"
echo "  Browse plugins : copilot plugin marketplace browse azure-skills"
echo "  Install plugin : copilot  →  /plugin install azure@azure-skills"
